language: node_js
node_js:
- '5'
addons:
  ssh_known_hosts: jseminck.be
install:
- travis_retry npm install -g node-gyp
- travis_retry npm install
- sleep 15
script:
- travis_retry npm run prebuild
- travis_retry npm run build
after_success:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- tar -czf package.tgz build
- sshpass -e scp package.tgz deploy@jseminck.be:/home/apps/
before_install:
- openssl aes-256-cbc -K $encrypted_37c42d1fc8f1_key -iv $encrypted_37c42d1fc8f1_iv
  -in deploy-key.enc -out deploy-key -d
